---

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 1:00 every day
    - cron: '*/2 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # We run this job on every PR, on every merge to master, and nightly.
      # This causes us to hit an issue with Codecov.
      #
      # We see "Too many uploads to this commit.".
      # See https://community.codecov.io/t/too-many-uploads-to-this-commit/2574.
      #
      # To work around this, we do not upload coverage data on scheduled runs.
      # We print the event name here to help with debugging.
      - name: "Show event name"
        run: |
          echo ${{ github.event_name }}

      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v1.0.13"
        with:
          fail_ci_if_error: true
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
